describe("Data Driven",()=>{
    it("Using Fixtures",()=>{
        cy.fixture('data_spicejet').then(data=>{
            cy.visit(data.url)
        //cy.get("div[class='css-76zvg2 r-jwli3a r-ubezar']").click()
       //cy.get("div[class='css-76zvg2 r-jwli3a r-ubezar']").click()
        cy.get('.col-sm-4 > .form-control').should("be.visible")
        cy.get('.col-sm-4 > .form-control').select("MR")
        cy.get('#first_name').should("be.visible").type(data.first_name)
        //cy.get('#first_name').should("Not.be.visible").type("Rahul")
        cy.get('#last_name').should("be.visible").type(data.last_name)
        cy.get(':nth-child(3) > :nth-child(1) > .form-control').should("be.visible").select("Guinea")
        cy.get('#dobDate').click().should("be.visible").type("16-December-2001")
        cy.get('.react-tel-input > .form-control').should("be.visible").type(data.contact)
        cy.get('#email_id').should("be.visible").click()
        cy.get('#email_id').should("be.visible").type(data.email_id)
        cy.get('#new-password').should("be.visible").click()
        cy.get('#new-password').should("be.visible").type(data.new_password)
        cy.get('#c-password').should("be.visible").click()
        cy.get('#c-password').should("be.visible").type(data.c_password)
        //cy.get('.form-check').check()
        cy.get('#defaultCheck1').should("be.visible").check()
        cy.get('.px-sm-4 > a > .btn').should("be.visible").click()
    })
})
})